version: 2

project_name: ghlabels

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "ghcr.io/kamontat/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/kamontat/{{ .ProjectName }}:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64

  - image_templates:
      - "ghcr.io/kamontat/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/kamontat/{{ .ProjectName }}:latest-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/kamontat/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/kamontat/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/kamontat/{{ .ProjectName }}:{{ .Version }}-arm64"

  - name_template: "ghcr.io/kamontat/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/kamontat/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/kamontat/{{ .ProjectName }}:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
